### PR TITLE
Exit with non-zero on error.

### PR DESCRIPTION
**Pull request by thebearingedge**
If there is an error, the return code should not be zero.

### CODE REVIEW

**Comment by shadorki** [comment]
I exit with 0 on error so the shell script will still delete the container after 😅 
I supposed we can just remove -e in the script tho ehe

**Comment by thebearingedge** [comment]
Will update 👍

**Comment by thebearingedge** [comment]
@uzair-ashraf Ok, I am mounting a volume into the container. The `output/` gets created only if it doesn't exist and the container gets removed on error or success.

**Comment by shadorki** [comment]
Somethings never change, tyimage

**Review by shadorki — APPROVED** [review]

**Comment by thebearingedge** [comment]
tenor

**Pull request merged**
